{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Colocations handled automatically by placer.\n",
      "100%|█████████████████████████████████████████████| 6/6 [00:18<00:00,  3.08s/it]\n"
     ]
    }
   ],
   "source": [
    "!python extract_features.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tqdm\n",
      "\u001b[?25l  Downloading https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl (48kB)\n",
      "\u001b[K    100% |████████████████████████████████| 51kB 24.5MB/s ta 0:00:01\n",
      "\u001b[?25hInstalling collected packages: tqdm\n",
      "Successfully installed tqdm-4.31.1\n",
      "\u001b[33mYou are using pip version 10.0.1, however version 19.0.3 is available.\n",
      "You should consider upgrading via the 'pip install --upgrade pip' command.\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Colocations handled automatically by placer.\n",
      "Found 13161 images belonging to 1 classes.\n",
      "Found 13161 images belonging to 1 classes.\n",
      "Loading network from ImageNet weights.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.cast instead.\n",
      "Epoch 1/10\n",
      "100/100 [==============================] - 71s 708ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 2/10\n",
      "100/100 [==============================] - 65s 650ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 3/10\n",
      "100/100 [==============================] - 67s 669ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 4/10\n",
      "100/100 [==============================] - 67s 670ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 5/10\n",
      "100/100 [==============================] - 67s 672ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 6/10\n",
      "100/100 [==============================] - 67s 671ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 7/10\n",
      "100/100 [==============================] - 68s 683ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 8/10\n",
      "100/100 [==============================] - 68s 679ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 9/10\n",
      "100/100 [==============================] - 68s 681ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 10/10\n",
      "100/100 [==============================] - 68s 684ms/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "Epoch 1/1000\n",
      "Traceback (most recent call last):\n",
      "  File \"train_cnn.py\", line 137, in <module>\n",
      "    main(weights_file)\n",
      "  File \"train_cnn.py\", line 133, in main\n",
      "    [checkpointer, early_stopper, tensorboard])\n",
      "  File \"train_cnn.py\", line 114, in train_model\n",
      "    callbacks=callbacks)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/legacy/interfaces.py\", line 91, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py\", line 1418, in fit_generator\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training_generator.py\", line 217, in fit_generator\n",
      "    class_weight=class_weight)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py\", line 1211, in train_on_batch\n",
      "    class_weight=class_weight)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py\", line 809, in _standardize_user_data\n",
      "    y, self._feed_loss_fns, feed_output_shapes)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training_utils.py\", line 273, in check_loss_and_target_compatibility\n",
      "    ' while using as loss `categorical_crossentropy`. '\n",
      "ValueError: You are passing a target array of shape (32, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:\n",
      "```\n",
      "from keras.utils import to_categorical\n",
      "y_binary = to_categorical(y_int)\n",
      "```\n",
      "\n",
      "Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.\n"
     ]
    }
   ],
   "source": [
    "!python train_cnn.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "Loading LSTM model.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Colocations handled automatically by placer.\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "lstm_1 (LSTM)                (None, 2048)              33562624  \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 512)               1049088   \n",
      "_________________________________________________________________\n",
      "dropout_1 (Dropout)          (None, 512)               0         \n",
      "_________________________________________________________________\n",
      "dense_2 (Dense)              (None, 1)                 513       \n",
      "=================================================================\n",
      "Total params: 34,612,225\n",
      "Trainable params: 34,612,225\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "None\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.cast instead.\n",
      "Epoch 1/1000\n",
      "Creating test generator with 137 samples.\n",
      "Creating train generator with 137 samples.\n",
      "5/5 [==============================] - 11s 2s/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "\n",
      "Epoch 00001: val_loss did not improve from inf\n",
      "Epoch 2/1000\n",
      "5/5 [==============================] - 8s 2s/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "\n",
      "Epoch 00002: val_loss did not improve from inf\n",
      "Epoch 3/1000\n",
      "5/5 [==============================] - 8s 2s/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "\n",
      "Epoch 00003: val_loss did not improve from inf\n",
      "Epoch 4/1000\n",
      "5/5 [==============================] - 8s 2s/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "\n",
      "Epoch 00004: val_loss did not improve from inf\n",
      "Epoch 5/1000\n",
      "5/5 [==============================] - 8s 2s/step - loss: nan - acc: 1.0000 - val_loss: nan - val_acc: 1.0000\n",
      "\n",
      "Epoch 00005: val_loss did not improve from inf\n"
     ]
    }
   ],
   "source": [
    "!python train.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "Loading C3D\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:198: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(64, (3, 3, 3), activation=\"relu\", name=\"conv1\", input_shape=(40, 80, 8..., strides=(1, 1, 1), padding=\"same\")`\n",
      "  input_shape=self.input_shape))\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Colocations handled automatically by placer.\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:200: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(pool_size=(1, 2, 2), strides=(1, 2, 2), name=\"pool1\", padding=\"valid\")`\n",
      "  border_mode='valid', name='pool1'))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:204: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(128, (3, 3, 3), activation=\"relu\", name=\"conv2\", strides=(1, 1, 1), padding=\"same\")`\n",
      "  subsample=(1, 1, 1)))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:206: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), name=\"pool2\", padding=\"valid\")`\n",
      "  border_mode='valid', name='pool2'))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:210: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(256, (3, 3, 3), activation=\"relu\", name=\"conv3a\", strides=(1, 1, 1), padding=\"same\")`\n",
      "  subsample=(1, 1, 1)))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:213: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(256, (3, 3, 3), activation=\"relu\", name=\"conv3b\", strides=(1, 1, 1), padding=\"same\")`\n",
      "  subsample=(1, 1, 1)))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:215: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), name=\"pool3\", padding=\"valid\")`\n",
      "  border_mode='valid', name='pool3'))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:219: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation=\"relu\", name=\"conv4a\", strides=(1, 1, 1), padding=\"same\")`\n",
      "  subsample=(1, 1, 1)))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:222: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation=\"relu\", name=\"conv4b\", strides=(1, 1, 1), padding=\"same\")`\n",
      "  subsample=(1, 1, 1)))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:224: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), name=\"pool4\", padding=\"valid\")`\n",
      "  border_mode='valid', name='pool4'))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:229: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation=\"relu\", name=\"conv5a\", strides=(1, 1, 1), padding=\"same\")`\n",
      "  subsample=(1, 1, 1)))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:232: UserWarning: Update your `Conv3D` call to the Keras 2 API: `Conv3D(512, (3, 3, 3), activation=\"relu\", name=\"conv5b\", strides=(1, 1, 1), padding=\"same\")`\n",
      "  subsample=(1, 1, 1)))\n",
      "/home/ubuntu/anaconda3/five-video-classification-methods-master/models.py:235: UserWarning: Update your `MaxPooling3D` call to the Keras 2 API: `MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), name=\"pool5\", padding=\"valid\")`\n",
      "  border_mode='valid', name='pool5'))\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "conv1 (Conv3D)               (None, 40, 80, 80, 64)    5248      \n",
      "_________________________________________________________________\n",
      "pool1 (MaxPooling3D)         (None, 40, 40, 40, 64)    0         \n",
      "_________________________________________________________________\n",
      "conv2 (Conv3D)               (None, 40, 40, 40, 128)   221312    \n",
      "_________________________________________________________________\n",
      "pool2 (MaxPooling3D)         (None, 20, 20, 20, 128)   0         \n",
      "_________________________________________________________________\n",
      "conv3a (Conv3D)              (None, 20, 20, 20, 256)   884992    \n",
      "_________________________________________________________________\n",
      "conv3b (Conv3D)              (None, 20, 20, 20, 256)   1769728   \n",
      "_________________________________________________________________\n",
      "pool3 (MaxPooling3D)         (None, 10, 10, 10, 256)   0         \n",
      "_________________________________________________________________\n",
      "conv4a (Conv3D)              (None, 10, 10, 10, 512)   3539456   \n",
      "_________________________________________________________________\n",
      "conv4b (Conv3D)              (None, 10, 10, 10, 512)   7078400   \n",
      "_________________________________________________________________\n",
      "pool4 (MaxPooling3D)         (None, 5, 5, 5, 512)      0         \n",
      "_________________________________________________________________\n",
      "conv5a (Conv3D)              (None, 5, 5, 5, 512)      7078400   \n",
      "_________________________________________________________________\n",
      "conv5b (Conv3D)              (None, 5, 5, 5, 512)      7078400   \n",
      "_________________________________________________________________\n",
      "zero_padding3d_1 (ZeroPaddin (None, 5, 7, 7, 512)      0         \n",
      "_________________________________________________________________\n",
      "pool5 (MaxPooling3D)         (None, 2, 3, 3, 512)      0         \n",
      "_________________________________________________________________\n",
      "flatten_1 (Flatten)          (None, 9216)              0         \n",
      "_________________________________________________________________\n",
      "fc6 (Dense)                  (None, 4096)              37752832  \n",
      "_________________________________________________________________\n",
      "dropout_1 (Dropout)          (None, 4096)              0         \n",
      "_________________________________________________________________\n",
      "fc7 (Dense)                  (None, 4096)              16781312  \n",
      "_________________________________________________________________\n",
      "dropout_2 (Dropout)          (None, 4096)              0         \n",
      "_________________________________________________________________\n",
      "dense_1 (Dense)              (None, 1)                 4097      \n",
      "=================================================================\n",
      "Total params: 82,194,177\n",
      "Trainable params: 82,194,177\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n",
      "None\n",
      "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.cast instead.\n",
      "2019-04-19 05:41:10.869685: E tensorflow/core/common_runtime/executor.cc:624] Executor failed to create kernel. Resource exhausted: OOM when allocating tensor of shape [3,3,3,128,256] and type float\n",
      "\t [[{{node training/Adam/zeros_4}}]]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1334, in _do_call\n",
      "    return fn(*args)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1319, in _run_fn\n",
      "    options, feed_dict, fetch_list, target_list, run_metadata)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [3,3,3,128,256] and type float\n",
      "\t [[{{node training/Adam/zeros_4}}]]\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"train.py\", line 110, in <module>\n",
      "    main()\n",
      "  File \"train.py\", line 107, in main\n",
      "    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)\n",
      "  File \"train.py\", line 81, in train\n",
      "    workers=4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/legacy/interfaces.py\", line 91, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py\", line 1418, in fit_generator\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training_generator.py\", line 94, in fit_generator\n",
      "    callbacks.set_model(callback_model)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/callbacks.py\", line 54, in set_model\n",
      "    callback.set_model(model)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/callbacks.py\", line 790, in set_model\n",
      "    self.sess = K.get_session()\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py\", line 206, in get_session\n",
      "    session.run(tf.variables_initializer(uninitialized_vars))\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 929, in run\n",
      "    run_metadata_ptr)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1152, in _run\n",
      "    feed_dict_tensor, options, run_metadata)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1328, in _do_run\n",
      "    run_metadata)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py\", line 1348, in _do_call\n",
      "    raise type(e)(node_def, op, message)\n",
      "tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor of shape [3,3,3,128,256] and type float\n",
      "\t [[node training/Adam/zeros_4 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:702) ]]\n",
      "\n",
      "Caused by op 'training/Adam/zeros_4', defined at:\n",
      "  File \"train.py\", line 110, in <module>\n",
      "    main()\n",
      "  File \"train.py\", line 107, in main\n",
      "    load_to_memory=load_to_memory, batch_size=batch_size, nb_epoch=nb_epoch)\n",
      "  File \"train.py\", line 81, in train\n",
      "    workers=4)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/legacy/interfaces.py\", line 91, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py\", line 1418, in fit_generator\n",
      "    initial_epoch=initial_epoch)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training_generator.py\", line 40, in fit_generator\n",
      "    model._make_train_function()\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py\", line 509, in _make_train_function\n",
      "    loss=self.total_loss)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/legacy/interfaces.py\", line 91, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/optimizers.py\", line 487, in get_updates\n",
      "    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/optimizers.py\", line 487, in <listcomp>\n",
      "    ms = [K.zeros(K.int_shape(p), dtype=K.dtype(p)) for p in params]\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py\", line 702, in zeros\n",
      "    v = tf.zeros(shape=shape, dtype=tf_dtype, name=name)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py\", line 1817, in zeros\n",
      "    output = fill(shape, constant(zero, dtype=dtype), name=name)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py\", line 3367, in fill\n",
      "    \"Fill\", dims=dims, value=value, name=name)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py\", line 788, in _apply_op_helper\n",
      "    op_def=op_def)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py\", line 507, in new_func\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 3300, in create_op\n",
      "    op_def=op_def)\n",
      "  File \"/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 1801, in __init__\n",
      "    self._traceback = tf_stack.extract_stack()\n",
      "\n",
      "ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [3,3,3,128,256] and type float\n",
      "\t [[node training/Adam/zeros_4 (defined at /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:702) ]]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!python train.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Environment (conda_tensorflow_p36)",
   "language": "python",
   "name": "conda_tensorflow_p36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
